### ISSUE TITLE
Can't connect to private repo

### ISSUE THREAD

**Issue by skipAtArk** [fpigerre/IssuesDownload#4]
Hi,

I've been trying to connect to a private repo to pull down our milestones, but have been unable to do so.
Could you post an example of the exact syntax to do so?
I have been digging around in the code, but the method listed below always returns null.

``` Java
 public GHRepository getRepository(String name) throws IOException {
        try {
            return root.retrieve().to("/repos/" + login + '/' + name, GHRepository.class).wrap(root);
        } catch (FileNotFoundException e) {
            return null;
        }
    }

```

Thanks,
Skip

**Comment by fpigerre** [comment]
Hello @skipAtArk,

It seems that you've mentioned code pertaining to [Kohsuke Kawaguchi's GitHub API for Java](http://github-api.kohsuke.org/).
In order to obtain a list of a repository's milestones, you will likely need to access the GitHub API through similar syntax to the following:

``` java
github.getUser("USER INFO").getRepository("REPOSITORY INFO").listMilestones(GHIssueState state);
```

This syntax is will depend on the requirements of your application, however, and how you wish to access a GitHub repository's milestones.
Unfortunately, I am not able to provide very detailed information as I am somewhat unfamiliar with the details workings of Kohsuke's GitHub API library.

Technical documentation regarding Kohsuke Kawaguchi's library, however, can be found through the [relevant JavaDocs](http://github-api.kohsuke.org/apidocs/index.html).

Kind regards,
psgs

**Comment by skipAtArk** [comment]
Thanks for this info!

I have it working now.
